# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3204bf4e6f3dca9cb076139a9c4b5047f9f596324f6cb152b2e184afe5091edd1cad7852cd1639dd29564d52b0894561ec9adeeb0d77addc781017bb50f25e4c

test:
  secret_key_base: bfe8cf2eb307d80da9f9a87065b598c7f1a1cd363319343a4f9487245d993afe15cbba303cf9d937359018e76ef86120de8359fa7f32ad1b27d4bac0eacca11e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
